# Generated by Django 4.2.6 on 2024-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0007_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
