# Generated by Django 4.2.6 on 2024-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0012_rename_description_repairrequest_description_of_damage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('replacement_issue', models.CharField(choices=[('bead', 'Bead Replacement'), ('clasp', 'Clasp Replacement'), ('string', 'String Replacement')], max_length=10)),
                ('address_line_1', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(choices=[('naxal', 'Naxal'), ('chabahil', 'Chabahil'), ('boudha', 'Boudha')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('accessory_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
