# Generated by Django 4.2.6 on 2024-03-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0014_resizingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementrequest',
            name='city',
        ),
    ]
