# Generated by Django 4.2.6 on 2024-03-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0015_remove_replacementrequest_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='eSewa_order_id',
            new_name='khalti_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='eSewa_payment_id',
            new_name='khalti_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='eSewa_payment_status',
            new_name='khalti_payment_status',
        ),
    ]
