# Generated by Django 4.2.6 on 2024-04-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0017_cart_created_at_alter_orderplaced_status_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
