# Generated by Django 4.2.6 on 2024-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0020_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='COD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('pickup_location', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=20)),
                ('delivery_time', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ordered',
        ),
    ]
