# Generated by Django 4.2.6 on 2024-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0021_cod_delete_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='delivery_time',
            field=models.CharField(choices=[('7-9', 'From 7 to 9'), ('4-6', 'From 4 to 6')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cod',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cod',
            name='pickup_location',
            field=models.CharField(choices=[('chabahil', 'Chabahil'), ('naxal', 'Naxal')], max_length=100),
        ),
    ]
