# Generated by Django 4.2.6 on 2024-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0023_transaction_alter_orderplaced_payment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('COD  ', 'COD')], default='Khalti', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Initiated', max_length=50),
        ),
    ]
