# Generated by Django 4.2.6 on 2024-05-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0024_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
