# Generated by Django 4.2.6 on 2024-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0025_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Initiated', max_length=50),
        ),
    ]
