# Generated by Django 4.2.7 on 2024-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0026_rename_payment_orderplaced_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('COD ', 'COD')], default='Khalti', max_length=100),
        ),
    ]
