# Generated by Django 4.2.7 on 2024-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadaz', '0027_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('COD', 'COD')], default='Khalti', max_length=100),
        ),
    ]
